spring:
  application: 
    name: client-service

server:
  port: 7001
  servlet:
    context-path: /
eureka:
  client:
    service-url:
      ##单点配置:
      defaultZone: http://127.0.0.1:8001/eureka/
  