spring:
  application: 
    name: feign-consumer
    
server:
  port: 7002
  servlet:
    context-path: /
eureka:
  client:
    service-url:
      ##单点配置:
      defaultZone: http://127.0.0.1:8001/eureka/

##断路器超时时间: 
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 5000


##feign的配置项:  
feign:
  ##启动feign的断路器功能
  hystrix:
    enabled: true   
  compression:
    request:
      min-request-size: 2048
      mime-types:
        - text/xml, application/xml, application/json
    response: 
      enabled: true
      
      
      
