spring:
  application: 
    name: consumer-service

server:
  port: 7002
  servlet:
    context-path: /consumer
eureka:
  client:
    service-url:
      ##单点配置:
      #defaultZone: http://eureka1:8001/eureka/
      ##高可用配置
      defaultZone: http://127.0.0.1:8001/eureka/,http://127.0.0.1:8002/eureka/
  